//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALMOXARIFADO
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Produtos { get; set; }
        public double Quantidade { get; set; }
    }
}
